<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'jalismrs\\bitwarden\\bitwardencommands' => '/BitwardenCommands.php',
                'jalismrs\\bitwarden\\bitwardenservice' => '/BitwardenService.php',
                'jalismrs\\bitwarden\\bitwardenservicedelegate' => '/BitwardenServiceDelegate.php',
                'jalismrs\\bitwarden\\model\\bitwardenitem' => '/Model/BitwardenItem.php',
                'jalismrs\\bitwarden\\model\\bitwardenlogin' => '/Model/BitwardenLogin.php',
                'jalismrs\\bitwarden\\model\\bitwardenstatus' => '/Model/BitwardenStatus.php',
                'jalismrs\\bitwarden\\model\\bitwardenuri' => '/Model/BitwardenUri.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
